# Generated by Django 4.1.4 on 2022-12-22 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
