# Generated by Django 4.1.4 on 2022-12-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.CharField(default='c57516f9', max_length=8),
        ),
    ]
