# Generated by Django 4.1.5 on 2023-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_board_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.CharField(blank=True, default='f94193d2', max_length=8, null=True),
        ),
    ]
